# Py <img src="https://img.icons8.com/officel/64/000000/olympic-torch.png"/> 's nifty features

### Nifty features for beginners like me!

PyTorch is a machine learning library that is (accoring to Akaash) really easy to learn and this notebook contains commands that can  be helpful while learning.
- torch.randin
- torch.rand
- torch.device
- torch.set_default_dtype
- torch.get_default_dtyoe

In [4]:
# Install Torch and other modules(using pip)
#!pip3 install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
# Import torch and other required modules
import torch

## torch.randint()
This is a function that creates a tensor that is filled with random integers.All you have to do is define this lower and upper bound of the range and the size of the tensor. 

In [5]:
# Example 
variable=torch.randint(0,100,(2,2),)
print(variable)
print(variable.dtype)

tensor([[98, 95],
        [83, 78]])
torch.int64


This will create a 2x2 tensor that will have random values between 0 & 100.

In [6]:
x=torch.randint(100,(1,1))
x

tensor([[88]])

This will create a tensor with only one value. Shorthand-  only defining high means that the range will be from 0(inclusive) to high(non-inclusive).

This function makes it easy to gnereate data when only dealing with integer values.

## torch.rand
Makes it easy to generate decimal tensors.

In [7]:
#Example  1
exRand=torch.rand(2,2,)
exRand

tensor([[0.4161, 0.1112],
        [0.8907, 0.2660]])

This will create the variable `exRand` with a dtype  of (2,2). Unlike `tensor.randint` where you have to define bounds and size, here you only need to define size as the range is fixed between 0 and 1

Breakage- how you would break a regular function.

## torch.device
This makes it easy to set the device a workload run on, especially when the workload can de distibuted.

In [8]:
x=torch.tensor([2,2],device=torch.device("opencl"))
y=torch.tensor(64,device=torch.device("cpu"))

RuntimeError: Unknown device type

This example allows the splitting of the workload of setiting variables(I know it is not a lot) between the CPU and GPU

In [9]:
cpu=torch.device("cpu")
gpu=torch.device("cuda")
dtype=torch.float32
exampleDeviceTensor = torch.rand(64,5, device=cpu, dtype=dtype)
print(exampleDeviceTensor)
print(exampleDeviceTensor.dtype)

tensor([[0.8565, 0.0929, 0.0849, 0.0449, 0.4318],
        [0.8825, 0.1779, 0.9275, 0.8265, 0.8575],
        [0.1627, 0.8546, 0.1331, 0.3326, 0.0106],
        [0.3199, 0.4527, 0.6805, 0.5143, 0.7702],
        [0.7916, 0.7808, 0.0562, 0.9405, 0.9606],
        [0.2017, 0.3221, 0.8636, 0.1459, 0.9821],
        [0.7241, 0.0272, 0.2199, 0.8623, 0.5089],
        [0.0706, 0.4975, 0.9425, 0.2352, 0.2214],
        [0.4398, 0.9135, 0.4286, 0.9124, 0.2970],
        [0.0271, 0.3626, 0.2397, 0.8993, 0.9710],
        [0.2877, 0.0062, 0.8659, 0.2818, 0.7314],
        [0.5901, 0.1829, 0.5442, 0.6905, 0.1259],
        [0.3730, 0.4185, 0.3691, 0.7199, 0.1676],
        [0.8761, 0.3521, 0.2423, 0.4345, 0.9179],
        [0.3732, 0.1929, 0.6609, 0.9573, 0.3858],
        [0.1261, 0.8841, 0.0240, 0.8538, 0.3983],
        [0.6285, 0.1921, 0.6312, 0.6876, 0.7981],
        [0.0418, 0.5002, 0.4993, 0.2673, 0.1363],
        [0.7098, 0.1342, 0.4372, 0.6597, 0.2816],
        [0.3744, 0.4372, 0.8668, 0.8017, 0.6141],


This **will** break when you don't have a compatible  graphics card.

In [10]:
exampleDeviceTensor = torch.randn(64,5, device=gpu, dtype=dtype)

AssertionError: Torch not compiled with CUDA enabled

I find this really nice, as you can just set it as a variable and apply the variable as needed depending on hardware configuration.

## torch.set_default_dtype
Sets the default data type for all new tensors.

In [11]:
before1=torch.tensor(2.3,dtype=torch.float64)
before1=torch.tensor(3.141519,dtype=torch.float64)
torch.set_default_dtype(torch.float64)
after1=torch.tensor(2.3)
after1.dtype

torch.float64

Instead of setting the type manually each time, set a different deafult dtype and change others as needed.

In [12]:
torch.set_default_dtype(torch.int64)
torch.set_default_dtype(torch.float32)

TypeError: only floating-point types are supported as the default type

Some of the dtypes available.(float32 is default)

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
torch.set_default_dtype(int32)

NameError: name 'int32' is not defined

Just don't forget to do torch.[dtype], not just the dtype itself

Handy when you already know the datatype for the model. I would recommend that it should be deined at the start of the funtion and not changed often(makes a harder read)

## torch.empty
Generate blank tensors!

In [14]:
# Example 1 - working
empty=torch.empty(3,4)
empty

tensor([[0.5688, 0.4185, 0.9610, 0.2012, 0.2568],
        [0.3763, 0.7459, 0.1615, 0.4732, 0.9705],
        [0.3049, 0.6540, 0.7104, 0.7375, 0.7971],
        [0.8616, 0.1783, 0.9092, 0.7025, 0.3565],
        [0.1676, 0.5751, 0.5586, 0.6405, 0.4409],
        [0.5301, 0.9040, 0.6713, 0.5315, 0.9289],
        [0.5358, 0.0139, 0.8581, 0.3591, 0.9962],
        [0.4570, 0.7147, 0.9151, 0.5119, 0.7621],
        [0.6426, 0.6709, 0.5946, 0.6951, 0.7664],
        [0.9177, 0.6028, 0.0797, 0.8435, 0.8044],
        [0.6811, 0.3764, 0.9063, 0.3905, 0.5328],
        [0.3256, 0.7304, 0.2361, 0.7386, 0.4042],
        [0.8457, 0.7612, 0.8361, 0.4281, 0.9700],
        [0.0814, 0.8485, 0.7536, 0.3545, 0.7375],
        [0.6571, 0.4044, 0.2198, 0.0438, 0.2349],
        [0.0879, 0.9232, 0.3923, 0.8138, 0.1040],
        [0.0666, 0.7938, 0.9507, 0.5446, 0.8988],
        [0.2631, 0.9771, 0.4614, 0.0081, 0.9538],
        [0.7693, 0.0612, 0.0274, 0.6614, 0.6241],
        [0.5723, 0.0991, 0.7895, 0.8838, 0.0203],


Generates a tensor of size 3.4

In [ ]:
Use this when you want to populate data later.

In [ ]:
## Conclusion

This notebook covered basic pytorch functions. A good thing to check out would be [freecodecamp.org] and [youtube.com/channel/TwoMinutePapers]

## Reference Links
* Official documentation for `torch`: https://pytorch.org/docs/stable/torch.html

In [17]:
!pip3 install jovian --upgrade --quiet

In [49]:
!jovian commit 01-tensor-operations.ipynb

[jovian] Uploading 1 notebook: 01-tensor-operations.ipynb

[jovian] Do you want to continue? [Y/n]: